<div class="row">
    <div class="span4">
        <div style="border: 1px solid black">
        <?php echo $this->sidebar; ?>
        </div>
    </div>
    <div class="span8">
        <div style="border: 1px solid black">
        <p>main content</p>
        <p>main content</p>
        <p>main content</p>
        <p>main content</p>
        <p>main content</p>
        <p>main content</p>
        </div>
    </div>
</div>
